id: ADECE61E2
title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:51:41.717176
  last_modified_at: 2022-03-01 05:51:41.717183
