id: ADECE61E2
title: Supplication to Lord Buddha together with the Sixteen Arhats
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:51:41.719115
  last_modified_at: 2022-03-01 05:51:41.719119
