id: ADECE61E2
title: A Brief Practice for Paying Homage and Making Offerings to the Buddha together
  with his retinue of Arhats
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:51:41.707462
  last_modified_at: 2022-03-01 05:51:41.707469
